import Head from 'next/head'
import TopNav from '../components/topnav'
import SideBar from '../components/sidebar'
import CompViewPage  from './componentview'
export default function Home() {
  // return (
  //   <div >
  //     <Head>
  //       <title>Snugle Web</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className="app relative flex">
  //       <SideBar />
  //       {/* Content */}
  //       <CompViewPage /> 
  //     </main>

      
  //   </div>
  // )

  return (
    <div class="flex">
    <aside class="bg-blue-800 h-screen sticky top-0 w-56 ">
        <SideBar />
    </aside>
    
    <main className="overflow-auto">
      <CompViewPage /> 
    </main>
</div>
  )
}
