import Head from "next/head";
import SideBar from "../components/sidebar";
import CompViewPage from "./componentview";
export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>Snugle Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside className="bg-blue-800 h-screen sticky top-0 w-64 transform -translate-x-full  md:relative md:translate-x-0 transition duration-200 ease-in-out">
        <SideBar />
      </aside>

      <main className="overflow-auto" id="main" style={{ width: "100%" }}>
        <CompViewPage />
      </main>
    </div>
  );
}
